version: '3.1'

services:
  app:
    build:
      context: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
      JWT_SECRET: thehardestsecretyouveeverseen
      REDIS_URL: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  redis:  
    image: redis:7.0.4-alpine
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
        - 8082:8081

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/